export const BlockType = {
    TemplateBlock: 'TemplateBlock',
    HeaderBlock: 'HeaderBlock',
    Header2Block: 'Header2Block',
    Header3Block: 'Header3Block',
    Header4Block: 'Header4Block',
    Header5Block: 'Header5Block',
    Header6Block: 'Header6Block',
    ParagraphBlock: 'ParagraphBlock',
    ImageBlock: 'ImageBlock',
    BlockquoteBlock: 'BlockquoteBlock',
    ListBlock: 'ListBlock',
    OrderedListBlock: 'OrderedListBlock',
    IEEEBlock: 'IEEEBlock',
    TableBlock: 'TableBlock',
    HorizontalRule: 'HorizontalRule',
    Center: 'Center',
    BlockId: 'BlockId',
    AlertBlock: "AlertBlock",
    TipBlock: "TipBlock",
    CodeBlock: "CodeBlock",
    Quotation: 'Quotation',
    YAMLBlock: 'YAMLBlock',
};

export const InlineType = {
    Text: 'Text',
    Italic: 'Italic',
    Bold: 'Bold',
    Code: 'Code',
    Tooltip: 'Tooltip',
    Anchor: 'Anchor',
    Emoji: 'Emoji',
    AnchorUri: 'AnchorUri',
    Id: 'Id',
    ListItem: 'ListItem',
    Checkbox: 'Checkbox',
    Superscript: 'Superscript',
    IEEEItem: 'IEEEItem',
    TableRow: 'TableRow',
    TableCell: 'TableCell',
    TableHeader: 'TableHeader',
    TableDelimiter: 'TableDelimiter',
    Small: 'Small',
    Big: "Big",
    Math: 'Math',
    Subscript: 'Subscript',
    CodeBlockFilename: 'CodeBlockFilename',
    CodeBlockLineNumbers: 'CodeBlockLineNumbers',
    QuoteAuthor: 'QuoteAuthor',
    Reference: 'Reference',
    Tab: 'Tab',
    Break: 'Break',
    Quip: 'Quip',
    Attributes: 'Attributes',
};